### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by yarom82** [yarom-and-shahar/cyclejs-shooter#25]

**Comment by mightyiam** [comment]
@yarom82 how would you like to be displayed in the credits?

**Comment by mightyiam** [comment]
I would like to be displayed like:
[Shahar Or (mightyiam)](http://mightyi.am)

**Comment by mightyiam** [comment]
blocked by #67

**Comment by mightyiam** [comment]
Since we're going to use a separate repo for deployment, this doesn't belong here. It belongs there.
